FROM python:3.9
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
ENV PORT 8080  # Ensure the environment variable is set
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
